[package]
name = "xactor-issue"
version = "0.1.0"
authors = ["James Collins <jracollins@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xactor = "0.7.3"
async-trait = "0.1.36"
futures = "0.3.5"
